---
title: "FinalProject"
author: "Yike Ma, Sean Burke, Evan Lim"
date: "2026-03-17"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Set Up
```{r}
library(here)
library(tidyverse)
library(dplyr)
```

# Read relevant datasets
```{r}
here()
#party.raw <- read.csv("./Data/countypres_2000-2024.csv")
violations.raw <- read.csv("./Data/SDWA_PN_VIOLATION_ASSOC.csv")
srf.raw <- read.csv("./Data/DW Assistance Provided.csv")

PWS.raw <- read.csv("./SDWA_PUB_WATER_SYSTEMS.csv") 

filefolder <- here('Data')

srf_files <- dir(filefolder, pattern = "srf_state_*.*", full.names = TRUE)

srf_data_2015to2025 <- srf_files %>% 
  map(read_csv) %>% 
  bind_rows()

srf_2021 <- read.csv(here("./Data/srf_state_2021.csv"))
srf_2022 <- read.csv(here("./Data/srf_state_2022.csv"))
srf_2023 <- read.csv(here("./Data/srf_state_2023.csv"))
srf_2024 <- read.csv(here("./Data/srf_state_2024.csv"))
srf_2025 <- read.csv(here("./Data/srf_state_2025.csv"))

srf_data_2021to2025 <- bind_rows(list(srf_2021, srf_2022, srf_2023, srf_2024, srf_2025))

srf_data_2023to2025 <- bind_rows(list(srf_2023, srf_2024, srf_2025))

```

# Data cleaning
```{r}
#party.clean <- party.raw %>% 
 # filter(year %in% c(2020, 2021, 2022, 2023, 2024)) %>% 
  #select("state","county_name","year","state_po","county_fips","party")

violations.raw$PWSID1 <- substring(violations.raw$PWSID,1,2) #The first two digits are country code
violations.clean <- violations.raw %>% 
  select("PWSID","VIOLATION_CODE","PWSID1") 

rows <- srf.raw[4,]
rows <- as.vector(rows)
srf <- srf.raw[-c(1:4),]
colnames(srf) <- rows

srf.clean <- srf %>% 
  select("State","Amount of New Funding")
srf.clean$`Amount of New Funding` <- as.numeric(gsub("\\,","",srf.clean$`Amount of New Funding`))

PWS.clean <- PWS.raw %>% 
  select("PWSID", "PWS_NAME","EPA_REGION","STATE_CODE")

violation.pws <- left_join(violations.clean,PWS.clean, by = c("PWSID" = "PWSID"))



violation.pws <- violation.pws %>%
   mutate(across(c(STATE_CODE, PWSID1), ~na_if(., "")))
violation.pws <- drop_na(violation.pws)

# Violations by each state
violation_totalbystate <- violation.pws %>% 
  count(STATE_CODE, sort = TRUE) %>% 
  filter(!(STATE_CODE %in% c("AS", "DC", "MP", "AB", "VI"))) %>% # removing these as we do not have corresponding SRF data
  mutate(State_Name = case_when(
    STATE_CODE == "AL" ~ "Alabama", STATE_CODE == "AK" ~ "Alaska",
    STATE_CODE == "AZ" ~ "Arizona", STATE_CODE == "AR" ~ "Arkansas",
    STATE_CODE == "CA" ~ "California", STATE_CODE == "CO" ~ "Colorado",
    STATE_CODE == "CT" ~ "Connecticut", STATE_CODE == "DE" ~ "Delaware",
    STATE_CODE == "FL" ~ "Florida", STATE_CODE == "GA" ~ "Georgia",
    STATE_CODE == "HI" ~ "Hawaii", STATE_CODE == "ID" ~ "Idaho",
    STATE_CODE == "IL" ~ "Illinois", STATE_CODE == "IN" ~ "Indiana",
    STATE_CODE == "IA" ~ "Iowa", STATE_CODE == "KS" ~ "Kansas",
    STATE_CODE == "KY" ~ "Kentucky", STATE_CODE == "LA" ~ "Louisiana",
    STATE_CODE == "ME" ~ "Maine", STATE_CODE == "MD" ~ "Maryland",
    STATE_CODE == "MA" ~ "Massachusetts", STATE_CODE == "MI" ~ "Michigan",
    STATE_CODE == "MN" ~ "Minnesota", STATE_CODE == "MS" ~ "Mississippi",
    STATE_CODE == "MO" ~ "Missouri", STATE_CODE == "MT" ~ "Montana",
    STATE_CODE == "NE" ~ "Nebraska", STATE_CODE == "NV" ~ "Nevada",
    STATE_CODE == "NH" ~ "New Hampshire", STATE_CODE == "NJ" ~ "New Jersey",
    STATE_CODE == "NM" ~ "New Mexico", STATE_CODE == "NY" ~ "New York",
    STATE_CODE == "NC" ~ "North Carolina", STATE_CODE == "ND" ~ "North Dakota",
    STATE_CODE == "OH" ~ "Ohio", STATE_CODE == "OK" ~ "Oklahoma",
    STATE_CODE == "OR" ~ "Oregon", STATE_CODE == "PA" ~ "Pennsylvania",
    STATE_CODE == "PR" ~ "Puerto Rico", STATE_CODE == "RI" ~ "Rhode Island",
    STATE_CODE == "SC" ~ "South Carolina", STATE_CODE == "SD" ~ "South Dakota",
    STATE_CODE == "TN" ~ "Tennessee", STATE_CODE == "TX" ~ "Texas",
    STATE_CODE == "UT" ~ "Utah", STATE_CODE == "VT" ~ "Vermont",
    STATE_CODE == "VA" ~ "Virginia", STATE_CODE == "WA" ~ "Washington",
    STATE_CODE == "WV" ~ "West Virginia", STATE_CODE == "WI" ~ "Wisconsin",
    STATE_CODE == "WY" ~ "Wyoming", TRUE ~ "Missing"))

#SRF Amount 2015-2025
srfcolnames <- c("State", "Amount")
colnames(srf_data_2015to2025) <- srfcolnames

srf_data_2015to2025 <- srf_data_2015to2025 %>% 
  group_by(State) %>% 
  summarize(total = sum(Amount))

colnames(srf_data_2015to2025) <- srfcolnames

srf_data_2015to2025 <- srf_data_2015to2025 %>% 
  mutate(Amount.mil = Amount/1000000)

srfcolnames15to25 <- c("State", "Amount10", "Amount.mil10")
colnames(srf_data_2015to2025) <- srfcolnames15to25

#SRF Amount 2021-2025
colnames(srf_data_2021to2025) <- srfcolnames

srf_data_2021to2025 <- srf_data_2021to2025 %>% 
  group_by(State) %>% 
  summarize(total = sum(Amount))

colnames(srf_data_2021to2025) <- srfcolnames

srf_data_2021to2025 <- srf_data_2021to2025 %>% 
  mutate(Amount.mil = Amount/1000000)

srfcolnames21to25 <- c("State", "Amount5", "Amount.mil5")
colnames(srf_data_2021to2025) <- srfcolnames21to25

#SRF Amount 2021-2025
colnames(srf_data_2023to2025) <- srfcolnames

srf_data_2023to2025 <- srf_data_2023to2025 %>% 
  group_by(State) %>% 
  summarize(total = sum(Amount))

colnames(srf_data_2023to2025) <- srfcolnames

srf_data_2023to2025 <- srf_data_2023to2025 %>% 
  mutate(Amount.mil = Amount/1000000)

srfcolnames23to25 <- c("State", "Amount3", "Amount.mil3")
colnames(srf_data_2023to2025) <- srfcolnames23to25

#SRF Amount 2025
colnames(srf_2025) <- srfcolnames

srf_2025 <- srf_2025 %>% 
  mutate(Amount.mil = Amount / 1000000)

srfcolnames25 <- c("State", "Amount1", "Amount.mil1")
colnames(srf_2025) <- srfcolnames25

# EPA regions
#srf_data_2015to2025 <- srf_data_2015to2025 %>% 
#  mutate(EPA.region = case_when(State %in% c("Connecticut", "Maine", 
#                                             "Massachusetts", "New Hampshire", 
#                                            "Rhode Island", "Vermont") ~ "Region 1",
#                                State %in% c("New Jersey", "New York", 
#                                             "Puerto Rico") ~ "Region 2",
#                                State %in% c("Delaware", "Washington DC", 
#                                             "Maryland", "Pennsylvania", 
#                                             "Virginia", "West Virginia") ~ "Region 3",
#                                State %in% c("Alabama", "Florida", "Georgia", 
#                                             "Kentucky", "Mississippi", 
#                                             "North Carolina", "South Carolina", 
#                                             "Tennessee") ~ "Region 4",
#                                State %in% c("Illinois", "Indiana", 
#                                             "Michigan", "Minnesota", 
#                                             "Ohio", "Wisconsin") ~ "Region 5",
#                                State %in% c("Arkansas", "Louisiana", 
#                                             "New Mexico", "Oklahoma", 
#                                             "Texas") ~ "Region 6",
#                                State %in% c("Iowa", "Kansas", 
#                                             "Missouri", "Nebraska") ~ "Region 7",
#                                State %in% c("Colorado", "Montana", 
#                                             "North Dakota", "South Dakota", 
#                                            "Utah", "Wyoming") ~ "Region 8",
#                                State %in% c("Arizona", "California", 
#                                             "Hawaii", "Nevada") ~ "Region 9",
#                                State %in% c("Alaska", "Idaho", 
#                                             "Oregon", "Washington") ~ "Region 10"))

```


```{r}
##Data preparing for the population dataset

pop1 <- read.csv("./Data/2010_2020pop.csv")
colnames(pop1 ) <- pop1[3,]
pop1 <- pop1[-c(1:8),]
pop1<- pop1[,-c(2:7)]
colnames(pop1) <- c("State","Y2015","Y2016","Y2017","Y2018","Y2019","Y2020")
pop1 <- pop1[-c(52:59),]

pop1$State <- gsub('\\.', '', pop1$State)
pop1$Y2015 <- as.numeric(gsub("\\,","",pop1$Y2015))
pop1$Y2016 <- as.numeric(gsub("\\,","",pop1$Y2016))
pop1$Y2017 <- as.numeric(gsub("\\,","",pop1$Y2017))
pop1$Y2018 <- as.numeric(gsub("\\,","",pop1$Y2018))
pop1$Y2019 <- as.numeric(gsub("\\,","",pop1$Y2019))
pop1$Y2020 <- as.numeric(gsub("\\,","",pop1$Y2020))


pop2 <- read.csv("./Data/2020_2025pop.csv")
pop2 <- pop2[,-c(1:4,6,7,13:97)]
colnames(pop2) <- c("State","Y2021","Y2022","Y2023","Y2024","Y2025")

pop <- left_join(pop1,pop2, by = "State")
pop$avg_2023_2025   <- rowMeans(pop[, c("Y2023","Y2024","Y2025")])
pop$avg_2021_2025   <- rowMeans(pop[, c("Y2021","Y2022","Y2023","Y2024",
                                        "Y2025")])
pop$avg_2015_2025   <- rowMeans(pop[, c("Y2015","Y2016","Y2017","Y2018","Y2019",
                                        "Y2020","Y2021","Y2022","Y2023","Y2024","Y2025")])

pop$avg_2015_2025 <- as.integer(pop$avg_2015_2025)

pop_final <- pop %>% 
  select("State", "avg_2023_2025", "avg_2021_2025", "avg_2015_2025", "Y2025")

```

```{r}
# Data prepping political affiliation data
political_record <- read.csv(here("./Data/Copy_of_Political_Affiliation.csv"))

political_record_avg_16to24 <- political_record %>% 
  select("State", "Political.Affiliation")
```


# Creating final dataframe
```{r}
# Updating column names to match
violationcols <- c("STATE_CODE", "Num_viol_2025", "State")
colnames(violation_totalbystate) <- violationcols

# Merging
all_variables <- violation_totalbystate %>% 
  left_join(pop_final, by = "State") %>% 
  left_join(srf_data_2015to2025, by = "State") %>% 
  left_join(srf_data_2021to2025, by = "State") %>% 
  left_join(srf_data_2023to2025, by = "State") %>% 
  left_join(srf_2025, by = "State") %>% 
  left_join(political_record_avg_16to24, by = "State")

# Transforming by pop / per capita
our_final_data <- all_variables %>% 
  mutate(Amount10_per_cap = Amount10/avg_2015_2025) %>% 
  mutate(Amount5_per_cap = Amount5/avg_2021_2025) %>% 
  mutate(Amount3_per_cap = Amount3/avg_2023_2025) %>% 
  mutate(Amount1_per_cap = Amount1/Y2025) %>% 
  mutate(Violations_per_cap = Num_viol_2025/Y2025) %>% 
  select("State", "Violations_per_cap", "Num_viol_2025", "Amount10_per_cap", "Amount5_per_cap",
         "Amount3_per_cap", "Amount1_per_cap","Political.Affiliation") %>% 
  drop_na() # Dropping PR as residents do not vote... maybe we consider running other analysis on just PR?
```


# Initial figure creation
```{r}
#ggplot(srf.clean, aes(x = `Amount of New Funding`))+
 # geom_histogram()

violation_state <- ggplot(violation.pws,aes(as.factor(x = STATE_CODE)))+
  geom_bar()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 60, hjust = 0.8))+
  labs(title = "Drinking Water Violations in 2025 by State",
       x = "State",
       y = "Count")
violation_state
ggsave(violation_state,
       filename = "MaYBurkeSLimEFig2.jpg",
       height = 15,
       width = 40,
       units = "cm")
```

```{r}
EPAregion_amt <- ggplot(srf_data_2015to2025, 
                        aes(x = EPA.region, 
                            y = Amount.mil)) +
  geom_bar(stat = "identity") +
  theme_bw()
  
state_amt <-  ggplot(srf_data_2015to2025, 
                        aes(x = State, 
                            y = Amount.mil)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  labs(y = "Amount (in millions USD)",
       title = "Drinking Water State Revolving Funds Assistance provided from 2015 - 2025 by State")

ggsave(state_amt,
       filename = "MaYBurkeSLimEFig1.jpg",
       height = 15,
       width = 40,
       units = "cm")
```


# Data exploration
```{r}
# Visualizing distributions of data

#Violations
ggplot(our_final_data,
       aes(x = State, y = Violations_per_cap)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

ggplot(our_final_data,
       aes(x = log(Violations_per_cap)))+
  geom_histogram()

ggplot(our_final_data,
       aes(x = log(Num_viol_2025)))+
  geom_histogram()
# SRF spending per state 2015-2025
ggplot(our_final_data,
       aes(x = State, y = Amount10_per_cap)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

# SRF spending per state 2021-2025
ggplot(our_final_data,
       aes(x = State, y = Amount5_per_cap)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

# SRF spending per state 2023-2025
ggplot(our_final_data,
       aes(x = State, y = Amount3_per_cap)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

# SRF spending per state 2025
ggplot(our_final_data,
       aes(x = State, y = Amount1_per_cap)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

# Political affiliation
ggplot(our_final_data,
       aes(x = Political.Affiliation)) +
  geom_bar(stat = "count") +
  theme_bw()

```

```{r}
# Visualizing relationships

# Violations and SRF Spending 2015 to 2025
ggplot(our_final_data,
       aes(x = Amount10_per_cap,
           y = Violations_per_cap)) +
  geom_jitter() +
  theme_bw()

# Violations and SRF Spending 2021 to 2025
ggplot(our_final_data,
       aes(x = Amount5_per_cap,
           y = Violations_per_cap)) +
  geom_jitter() +
  theme_bw()

# Violations and SRF Spending 2023 to 2025
ggplot(our_final_data,
       aes(x = Amount3_per_cap,
           y = Violations_per_cap)) +
  geom_jitter() +
  theme_bw()

# Violations and SRF Spending 2025
ggplot(our_final_data,
       aes(x = Amount1_per_cap,
           y = Violations_per_cap)) +
  geom_jitter() +
  theme_bw()

# Violations and Political Affiliation
ggplot(our_final_data,
       aes(x = Political.Affiliation,
           y = Violations_per_cap)) +
  geom_boxplot() +
  theme_bw()

# Political Affiliation and SRF 10
ggplot(our_final_data,
       aes(x = Political.Affiliation,
           y = Amount10_per_cap)) +
  geom_boxplot() +
  theme_bw()

# Political Affiliation and SRF 5
ggplot(our_final_data,
       aes(x = Political.Affiliation,
           y = Amount5_per_cap)) +
  geom_boxplot() +
  theme_bw()

# Political Affiliation and SRF 3
ggplot(our_final_data,
       aes(x = Political.Affiliation,
           y = Amount3_per_cap)) +
  geom_boxplot() +
  theme_bw()

# Political Affiliation and SRF 1
ggplot(our_final_data,
       aes(x = Political.Affiliation,
           y = Amount1_per_cap)) +
  geom_boxplot() +
  theme_bw()


```

# Check the correlation between variables
```{r}

```



# Model fitting
```{r}
#Poisson regression using counts of violation

#transform the political affiliation (categorical variables) into factors
our_final_data$Political.Affiliation <- factor(our_final_data$Political.Affiliation, 
                             level = c("R",
                                       "D",
                                       "Other"))

mod_poisson1yr <- glm(data = our_final_data, Num_viol_2025 ~ Amount1_per_cap + Political.Affiliation, family = "poisson")
summary(mod_poisson1yr)

mod_poisson3yr <- glm(data = our_final_data, Num_viol_2025 ~ Amount3_per_cap + Political.Affiliation, family = "poisson")
summary(mod_poisson3yr)

mod_poisson5yr <- glm(data = our_final_data, Num_viol_2025 ~ Amount5_per_cap + Political.Affiliation, family = "poisson")
summary(mod_poisson5yr)

mod_poisson10yr <- glm(data = our_final_data, Num_viol_2025 ~ Amount10_per_cap + Political.Affiliation, family = "poisson")
summary(mod_poisson10yr)

AIC(mod_poisson1yr, mod_poisson3yr)
AIC(mod_poisson3yr, mod_poisson5yr)
AIC(mod_poisson5yr, mod_poisson10yr) # 10yr has the lowest AIC


mod_poissontest <- glm(data = our_final_data, Num_viol_2025 ~ Amount1_per_cap + Political.Affiliation + Y2025, family = "poisson")
summary(mod_poissontest)

# lm
mod2 <- lm(data = our_final_data, log(Violations_per_cap) ~ Amount1_per_cap + Political.Affiliation)
summary(mod2)
plot(mod2)

```

